### ISSUE TITLE
studio: display tags on all cards of the main feed

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#371]
## Description

Currently on the main feed ("the home screen") of the editor ("studio"), the tags (hashtags like `#javascript #tech` etc.) are only displayed on the first card of the list.

I think it would be cool to display them on each card.

### Current display

First card:

Screenshot
Title
Author + date
Description
Tags

Other cards

Screenshot
Title
Author + date

### Goal

First card:

Screenshot
Title
Author + date
Description
Tags

Other cards

Screenshot
Title
Author + date
Tags <----------- TODO

**Comment by himankpathak** [comment]
Hi @peterpeterparker,  I would like to work on this issue. I got a hiccup while building DeckDeckGo Studio.
while running  `npm run start` I am getting the following error:

```
[ ERROR ]  Cannot find module './config.dev.json' Require stack: -
           /home/github/deckdeckgo/studio/stencil.config.ts -
           /home/github/deckdeckgo/studio/node_modules/@stencil/core/dist/sys/node/index.js -
           /home/github/deckdeckgo/studio/node_modules/@stencil/core/bin/stencil Error: Cannot find module
           './config.dev.json' Require stack: - /home/github/deckdeckgo/studio/stencil.config.ts -
           /home/github/deckdeckgo/studio/node_modules/@stencil/core/dist/sys/node/index.js -
           /home/github/deckdeckgo/studio/node_modules/@stencil/core/bin/stencil at
           Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15) at Function.Module._load
           (internal/modules/cjs/loader.js:677:27) at Module.require (internal/modules/cjs/loader.js:830:19) at require
           (internal/modules/cjs/helpers.js:68:18) at Object.<anonymous>
           (/home/github/deckdeckgo/studio/stencil.config.ts:14:41) at Module._compile
           (internal/modules/cjs/loader.js:936:30) at Object.require.extensions..ts
           (/home/github/deckdeckgo/studio/node_modules/@stencil/core/dist/sys/node/index.js:4817:16) at
           Module.load (internal/modules/cjs/loader.js:790:32) at Function.Module._load
           (internal/modules/cjs/loader.js:703:12) at Module.require (internal/modules/cjs/loader.js:830:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by peterpeterparker** [comment]
@himankpathak cool, happy to hear you would like to have a look at this issue 👍 

the configuration (tokens and keys) is not exposed in the repo (https://github.com/deckgo/deckdeckgo/blob/master/CONTRIBUTING.md). drop me a msg per mail or on slack, I'll be happy to share these info per PM
