### ISSUE TITLE
[Windows] Running locally errors out

### ISSUE THREAD

**Issue by dotNetkow** [deckgo/deckdeckgo#697]
### Affected part of DeckDeckGo
- [ ] Studio
- [ ] Remote control
- [ ] Documentation
- [ ] Demo
- [X] Starter kit
- [ ] Poll
- [ ] Web Components
- [ ] Templates

### Reproduction

Steps to reproduce:
1. Begin with a Starter or [Ionic React presentation](https://github.com/ionic-team/present-ionic-react) on Windows 10.
2. Run "npm install" then "npm run start" to kick off local hosting.
3. The start command fails, with following error and stacktrace:

webpack is watching the files...
[0]
[0] (node:7248) ExperimentalWarning: The fs.promises API is experimental
[0] Error: EPERM: operation not permitted, lstat 'C:\src\ionic\present-ionic-react\dist\svg\add-circle-outline.svg'
[0]     at Object.lstatSync (fs.js:845:3)
[0]     at Function.rimrafSync [as sync] (C:\src\ionic\present-ionic-react\node_modules\rimraf\rimraf.js:299:24)
[0]     at globby.sync.map.file (C:\src\ionic\present-ionic-react\node_modules\del\index.js:65:11)
[0]     at Array.map (<anonymous>)
[0]     at module.exports.sync (C:\src\ionic\present-ionic-react\node_modules\del\index.js:57:40)
[0]     at CleanWebpackPlugin.removeFiles (C:\src\ionic\present-ionic-react\node_modules\clean-webpack-plugin\dist\clean-webpack-plugin.js:198:37)
[0]     at CleanWebpackPlugin.handleInitial (C:\src\ionic\present-ionic-react\node_modules\clean-webpack-plugin\dist\clean-webpack-plugin.js:135:10)
[0]     at hooks.emit.tap.compilation (C:\src\ionic\present-ionic-react\node_modules\clean-webpack-plugin\dist\clean-webpack-plugin.js:84:16)
[0]     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)
[0]     at AsyncSeriesHook.lazyCompileHook (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\Hook.js:154:20)
[0]     at Compiler.emitAssets (C:\src\ionic\present-ionic-react\node_modules\webpack\lib\Compiler.js:491:19)
[0]     at onCompiled (C:\src\ionic\present-ionic-react\node_modules\webpack\lib\Watching.js:51:19)
[0]     at hooks.afterCompile.callAsync.err (C:\src\ionic\present-ionic-react\node_modules\webpack\lib\Compiler.js:681:15)      
[0]     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
[0]     at AsyncSeriesHook.lazyCompileHook (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\Hook.js:154:20)
[0]     at compilation.seal.err (C:\src\ionic\present-ionic-react\node_modules\webpack\lib\Compiler.js:678:31)
[0]     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
[0]     at AsyncSeriesHook.lazyCompileHook (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\Hook.js:154:20)
[0]     at hooks.optimizeAssets.callAsync.err (C:\src\ionic\present-ionic-react\node_modules\webpack\lib\Compilation.js:1423:35)[0]     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
[0]     at AsyncSeriesHook.lazyCompileHook (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\Hook.js:154:20)
[0]     at hooks.optimizeChunkAssets.callAsync.err (C:\src\ionic\present-ionic-react\node_modules\webpack\lib\Compilation.js:1414:32)
[0]     at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
[0]     at AsyncSeriesHook.lazyCompileHook (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\Hook.js:154:20)
[0]     at hooks.additionalAssets.callAsync.err (C:\src\ionic\present-ionic-react\node_modules\webpack\lib\Compilation.js:1409:36)
[0]     at _err0 (eval at create (C:\src\ionic\present-ionic-react\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
[0]     at handleCompilationDonePromise.then (C:\src\ionic\present-ionic-react\node_modules\html-webpack-plugin\lib\cached-child-compiler.js:267:53)
[0]     at process._tickCallback (internal/process/next_tick.js:68:7)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! present-ionic-react@1.0.0 watch: `webpack --watch --mode development`
[0] npm ERR! Exit status 1
npm ERR!
[0] npm ERR! Failed at the present-ionic-react@1.0.0 watch script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! present-ionic-react@1.0.0 start: `concurrently --kill-others "npm run watch" "npm run dev"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the present-ionic-react@1.0.0 start script.
 
### Expected Behavior

Presentation runs and opens on localhost.

### Actual Behavior

Oddly enough, if I run "npm run start" exactly 3 times, it works. It always takes 3 times before it works. 

### Environment

- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by peterpeterparker** [comment]
@dotNetkow thx for the hint! 

sounds like exactly like this issue https://github.com/deckgo/deckdeckgo-starter/issues/39 which we didn't solved yet.

it's a bug in the `clean-webpack-plugin` plugin which should be solved according issues I browser but well, seems not in our case.

P.S.:  if someone who develop on windows who help with this that would be cool

**Comment by dotNetkow** [comment]
Yeah, Webpack, not DDG - DDG works like a charm. :)

Ah, sorry! Odd, GitHub didn't show that other issue when I was typing this up. Feel free to close as duplicate if you'd like.

**Comment by peterpeterparker** [comment]
@dotNetkow no no it's good, it reminds us it's not solved and therefore still to be done. 

the other one is in another repo, therefor it's good to have one here too as reminder and specially also for contributors in case someone would be up to solve it
